site_name: Bixal Techbook
repo_url: https://github.com/Bixal/techbook/
site_url: https://bixal-techbook.bixal.com/en/latest/

theme:
    name: 'windmill-dark'
    custom_dir: 'theme/bixal-dark/mkdocs_windmill_dark'
    # default from mkdocs_theme.yml
    static_templates:
        - 404.html
    include_search_page: true
    search_index_only: true
    history_buttons: true
    article_nav_top: true
    article_nav_bottom: true

markdown_extensions:
    - mdx_truly_sane_lists
    - toc:
        permalink: '#'

extra:
    version: 0.1.4
